import {flushSync} from 'react-dom';
import WelcomeScreen from './WelcomeScreen.jsx';
import DesktopNotes from './DesktopNotes.jsx';
import AboutCanvas from './AboutCanvas.jsx';
import Applications from './Applications.jsx';
import Movies from './Movies.jsx';
import React,{useState,useEffect,useRef,useLayoutEffect} from 'react';
import{createRoot}from'react-dom/client';
import {Apple,Wifi,BatteryFull,Search,SlidersHorizontal,ChevronLeft,ChevronRight,Grid2X2,List,Folder,House,Clock,Star,Download,Cloud,Briefcase,User,Mail,Globe,Music2,Settings,Trash2,FileText,ArrowUpRight,Sun,ExternalLink,LayoutGrid,Check} from './symbols.jsx';
import'./styles.css';
import {genie} from './windowMotion.js';
import RecoveryStory from './RecoveryStory.jsx';
import TroskyStory from './TroskyStory.jsx';
import {ProjectBrowser,QuickLook} from './projects.jsx';
const sections=['Overview','Projects','About me','Contact'];
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function magnify(event){if(event.pointerType==='touch'||reduced())return;event.currentTarget.querySelectorAll('.dock-item').forEach(item=>{const r=item.getBoundingClientRect();const distance=Math.abs(event.clientX-(r.left+r.width/2));const strength=Math.max(0,1-distance/145);item.style.setProperty('--zoom',1+strength*.38);item.style.setProperty('--lift',`${-strength*12}px`);});}
function resetDock(event){event.currentTarget.querySelectorAll('.dock-item').forEach(item=>{item.style.setProperty('--zoom',1);item.style.setProperty('--lift','0px');});}
function bounce(event){const img=event.target.closest('button')?.querySelector('img');if(img&&!reduced())img.animate([{transform:'translateY(0)'},{transform:'translateY(-19px)',offset:.35},{transform:'translateY(0)',offset:.65},{transform:'translateY(-6px)',offset:.82},{transform:'translateY(0)'}],{duration:560,easing:'ease-out'});}
function App(){const[notesMode,setNotesMode]=useState(false);const[size,setSize]=useState(null);const resizeStart=useRef(null),minimized=useRef(false),motionSequence=useRef(0);const[preview,setPreview]=useState(null);const windowRef=useRef(null),closeAnimation=useRef(null),previousBounds=useRef(null);const[section,setSection]=useState('Overview'),[open,setOpen]=useState(false),[max,setMax]=useState(false),[time,setTime]=useState(new Date()),[dark,setDark]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState('');useEffect(()=>{let id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]);useEffect(()=>{if(notice){let id=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(id)}},[notice]);useLayoutEffect(()=>{const el=windowRef.current;if(!el||reduced())return;if(previousBounds.current){const old=previousBounds.current,next=el.getBoundingClientRect();el.animate([{transformOrigin:'top left',transform:`translate(${old.left-next.left}px,${old.top-next.top}px) scale(${old.width/next.width},${old.height/next.height})`},{transformOrigin:'top left',transform:'none'}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'});previousBounds.current=null;}},[max]);
const dockTarget=()=>document.querySelector('.dock-item.finder');
useLayoutEffect(()=>{if(open&&minimized.current&&windowRef.current){minimized.current=false;if(!reduced()){const anim=genie(windowRef.current,dockTarget(),true);closeAnimation.current=anim;anim.finished.catch(()=>{}).finally(()=>{anim.cleanup();if(closeAnimation.current===anim)closeAnimation.current=null;});}}},[open]);
useEffect(()=>{const fit=()=>setSize(s=>s?{width:Math.min(s.width,window.innerWidth-24),height:Math.min(s.height,window.innerHeight-155)}:s);window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit)},[]);
const resizeWindow=(dx,dy)=>{const r=resizeStart.current||windowRef.current.getBoundingClientRect();setSize({width:Math.max(Math.min(540,window.innerWidth-24),Math.min(window.innerWidth-24,r.width+dx*2)),height:Math.max(Math.min(340,window.innerHeight-155),Math.min(window.innerHeight-155,r.height+dy*2))});};
const hide=async(minimize)=>{const el=windowRef.current;if(!el)return;const ticket=++motionSequence.current;closeAnimation.current?.cancel();closeAnimation.current=null;minimized.current=minimize;if(reduced()){setOpen(false);return;}const animation=minimize?genie(el,dockTarget()):el.animate([{opacity:1,transform:'none'},{opacity:0,transform:'scale(.96) translateY(8px)'}],{duration:180,fill:'forwards'});closeAnimation.current=animation;try{await animation.finished;if(ticket===motionSequence.current){el.style.visibility='hidden';flushSync(()=>setOpen(false));};}catch{}finally{if(closeAnimation.current===animation)closeAnimation.current=null;animation.cleanup?.();}};
const go=s=>{setNotesMode(false);motionSequence.current++;closeAnimation.current?.cancel();closeAnimation.current=null;setSection(s);setOpen(true);setQuery('')};return <><div className={'desktop '+(dark?'night':'')}>
<div className="wallpaper"/><AboutCanvas covered={open||notesMode} onWork={()=>go('Projects')} onAbout={()=>go('About me')}/>{notesMode&&<DesktopNotes covered={open}/>}<header className="menubar"><div className="menu-left"><Apple size={18} fill="currentColor"/><b>Yogesh’s space</b><button onClick={()=>{setNotesMode(false);if(open)hide(true)}}>Home</button><button onClick={()=>go('Projects')}>Work</button><button onClick={()=>go('About me')}>About</button><button onClick={()=>go('Contact')}>Contact</button></div><div className="menu-right"><button aria-label="Toggle appearance" onClick={()=>setDark(!dark)}><Sun size={16}/></button><Wifi size={17}/><BatteryFull size={23}/><button aria-label="Search projects" onClick={()=>{go('Projects');setTimeout(()=>document.querySelector('input')?.focus(),30)}}><Search size={16}/></button><SlidersHorizontal size={16}/><span>{time.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})} <span className="time">{time.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</span></span></div></header>
<div className="desktop-label"><span>MAKE YOURSELF AT HOME</span><h1>A little space.<br/>A lot of possibilities.</h1></div>
<div className="desktop-files">{[[Folder,'Projects','Projects'],[FileText,'About me','About me'],[Mail,'Say hello','Contact']].map(([I,label,s])=><button key={label} onClick={()=>go(s)}><div className={'desktop-file '+(I===Folder?'folder-icon':'')}><img src={`/icons/${I===Folder?"folder":I===Mail?"mail":"document"}.png`} alt=""/></div><span>{label}</span></button>)}<Movies/></div>
{open?<main ref={windowRef} style={!max&&size?{width:size.width,height:size.height,maxWidth:'calc(100vw - 24px)',maxHeight:'calc(100svh - 155px)',flexShrink:0}:undefined} className={'window '+(max?'maximized':'')}><div className="window-bar"><div className="traffic"><button className="red" aria-label="Close window" onClick={()=>hide(false)}/><button className="yellow" aria-label="Minimize window" onClick={()=>hide(true)}/><button className="green" aria-label="Toggle maximize" onClick={()=>{previousBounds.current=windowRef.current?.getBoundingClientRect();setMax(!max)}}/></div><div className="window-tools"><div className="history"><button aria-label="Back to overview" onClick={()=>go('Overview')}><ChevronLeft size={20}/></button><ChevronRight size={20}/></div><b>{section}</b><div className="view-tools"><Grid2X2 size={17}/><span/><List size={19}/><Search size={17}/></div></div></div><div className="window-body"><aside><small className="sidebar-label">Favorites</small><nav>{sections.map((s,i)=>{let I=[House,Briefcase,User,Mail][i];return <button className={section===s?'selected':''} key={s} onClick={()=>go(s)}><I size={18}/>{s}{s==='Projects'&&<span>03</span>}</button>})}</nav><small className="sidebar-label second">Quick access</small><button className="side-link" onClick={()=>go('Projects')}><Clock size={17}/>Recent work</button><button className="side-link" onClick={()=>{go('About me');setNotice('You’ll find my experience in About me.')}}><Star size={17}/>Experience</button></aside><section key={section} className="content">
{section==='Overview'?<><div className="breadcrumb">My workspace <ChevronRight size={13}/> Overview</div><div className="welcome"><div className="eyebrow"><span>✦</span> Ideas, craft & a little curiosity</div><h2>Hello, I’m Yogesh<span>.</span><br/><em>Welcome to my corner.</em></h2><p>A curious mind with a love for thoughtful design<br className="desktop-break"/> and digital experiences that feel just right.</p><button className="primary" onClick={()=>go('Projects')}>Explore my work <ArrowUpRight size={16}/></button><div className="hero-symbol">✳</div></div><div className="section-heading"><h3>Around my workspace</h3><span>3 items</span></div><div className="cards">{[[Folder,'Selected work','Ideas brought to life','Projects','blue'],[User,'Behind the screen','A little more about me','About me','purple'],[Mail,'Let’s connect','Good things start with hello','Contact','orange']].map(([I,title,desc,s,c])=><button className="card" key={title} onClick={()=>go(s)}><div className={'card-icon '+c}><img src={`/icons/${I===Folder?"folder":I===User?"contacts":"mail"}.png`} alt=""/></div><ArrowUpRight className="card-arrow" size={17}/><h4>{title}</h4><p>{desc}</p></button>)}</div><div className="note"><div className="note-icon">✧</div><div><b>Always exploring. Always creating.</b><p>This space is a work in progress. Just like me.</p></div><span>Made with intention ↗</span></div></>:section==='Projects'?<><ProjectBrowser query={query} onPreview={setPreview}/></>:section==='About me'?<><div className="breadcrumb">My workspace <ChevronRight size={13}/> About me</div><div className="about-mark">y.</div><h2 className="page-title">The person behind<br/>the pixels<span>.</span></h2><p className="intro about-copy">Hi, I’m Yogesh. This is my personal corner of the internet — a place for the things I build, the ideas I’m exploring, and what comes next.</p><div className="about-tags"><span>Thoughtful design</span><span>Digital experiences</span><span>Constant curiosity</span></div><div className="note"><Star/><div><b>A little more, soon.</b><p>My experience and story will find a home here.</p></div></div></>:<><div className="breadcrumb">My workspace <ChevronRight size={13}/> Contact</div><div className="contact-mark"><Mail size={40}/></div><h2 className="page-title">Good things start<br/>with hello<span>.</span></h2><p className="intro about-copy">Have an idea, a project, or just something interesting to share? I’d love to connect.</p><div className="contact-info"><Mail size={20}/><div><b>Contact details coming soon</b><p>This workspace is still taking shape. Check back for ways to get in touch.</p></div></div></>}
</section></div>{!max&&<button className="window-resize" aria-label="Resize window. Drag or use arrow keys. Double click to reset." title="Drag to resize · Double-click to reset" onDoubleClick={()=>setSize(null)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();resizeStart.current=null;resizeWindow(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0,e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)}}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const r=windowRef.current.getBoundingClientRect();resizeStart.current={width:r.width,height:r.height,x:e.clientX,y:e.clientY};}} onPointerMove={e=>{const r=resizeStart.current;if(r&&e.currentTarget.hasPointerCapture(e.pointerId))resizeWindow(e.clientX-r.x,e.clientY-r.y)}} onPointerUp={e=>{resizeStart.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onLostPointerCapture={()=>{resizeStart.current=null}}>◢</button>}</main>:null}
<div className="dock-wrap"><div className="dock" onPointerMove={magnify} onPointerLeave={resetDock} onClickCapture={bounce}><Applications/>{[[House,'Home','finder','Overview'],[Briefcase,'Projects','safari','Projects'],[User,'About me','photos','About me'],[Mail,'Contact','mail','Contact']].map(([I,label,c,s])=><button className={'dock-item '+c} key={label} onClick={()=>go(s)} aria-label={label}><img src={`/icons/${c==="finder"?"finder":c==="safari"?"folder":c==="photos"?"contacts":"mail"}.png`} alt=""/><span className="tooltip">{label}</span>{open&&section===s&&<i/>}</button>)}<button className="dock-item notes" aria-label="Open Notes" onClick={()=>{setNotesMode(true);if(open)hide(true);else setTimeout(()=>document.getElementById('desktop-note')?.focus(),0)}}><img src="/icons/notes.png" alt=""/><span className="tooltip">Notes</span></button><div className="dock-divider"/><button className="dock-item settings" aria-label="Change appearance" onClick={()=>setDark(!dark)}><img src="/icons/settings.png" alt=""/><span className="tooltip">Appearance</span></button><button className="dock-item bin" aria-label="Trash" onClick={()=>setNotice('The Trash is empty. A fresh start!')}><img src="/icons/trash.png" alt=""/><span className="tooltip">Trash</span></button></div></div>{notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
</div>{preview&&<QuickLook project={preview} onClose={()=>setPreview(null)}/>}</>};createRoot(document.getElementById('root')).render(window.location.pathname==='/trosky'?<div className="standalone-case"><a className="back-portfolio" href="/">← Back to portfolio</a><TroskyStory/></div>:window.location.pathname==='/recovery'?<div className="standalone-case"><a className="back-portfolio" href="/">← Back to portfolio</a><RecoveryStory/></div>:<WelcomeScreen><App/></WelcomeScreen>);
