// Curated answers grounded in AboutMe.jsx, Experience.jsx and projects.jsx.
const topics = [
  {id:'contact', match:/contact|email|phone|reach|hire|available|availability|salary|rate|linkedin/i, text:'You can reach me directly at yogeshbattula55@gmail.com or connect with me on LinkedIn at linkedin.com/in/yogesh-battula. I’m always open to discussing new products and collaborations!', section:'Contact', action:'View contact info', source:'Contact'},
  {id:'resume', match:/resume|résumé|cv|download/i, text:'My résumé is available right here in the workspace. Open it to read or download the PDF.', section:'Resume', action:'Open résumé', source:'Résumé'},
  {id:'recovery', match:/recovery|rehab|health|patient|surgeon/i, text:'Recovery is a clinical rehabilitation platform connecting surgeons, physiotherapists, and patients. My case study covers shared onboarding, exercise tracking, progress dashboards, and care-team coordination. Detailed outcome metrics aren’t published.', section:'Projects', action:'Explore case studies', source:'Recovery case study'},
  {id:'trosky', match:/trosky|baseball|coach/i, text:'Trosky 365 is an AI-guided baseball coaching experience. I designed a conversational training companion that turns daily assignments and complex athletic mechanics into a guided coaching journey.', section:'Projects', action:'Explore case studies', source:'Trosky 365 · About'},
  {id:'experience', match:/experience|compan|career|worked|working|job|paradigm|prasthana|scrum|build up/i, text:'I’m a Product Designer at ParadigmIT (Aug 2025–present). Previously, I worked as a freelance Scrum Master (Jan–Aug 2025), Sr. Product Designer / Scrum Master & UX Designer at Prasthana Software Solutions (May 2022–Dec 2024), and UI Designer intern at BUILD UP (Jan–Apr 2022).', section:'Experience', action:'View experience', source:'Experience'},
  {id:'tools', match:/tool|figma|code|skill|photoshop|jira|stack|design system|vibe/i, text:'My primary stack is Figma and production code with full-stack AI vibe coding. Over the last year, I trained like a pro to take digital products from initial spark to live deployment on the web.', section:'About me', action:'More about me', source:'About · Applications'},
  {id:'cooking', match:/cook|food|culinary|chef|recipe|kitchen/i, text:'I love cooking! I treat it as a mindful culinary art—harmonizing fresh spices, slow cooking, and creating wholesome dishes that bring friends and family together.', section:'About me', action:'More about me', source:'About'},
  {id:'spiritual', match:/spirit|mindful|zen|peace|faith|soul|meditat/i, text:'I am deeply spiritual and grounded. It shapes how I approach life and design: bringing calmness, patience, and intentional clarity to everything I create.', section:'About me', action:'More about me', source:'About'},
  {id:'gadgets', match:/gadget|car|drive|auto|drone|hardware/i, text:'I’m fascinated by cutting-edge tech gadgets (spatial tech, custom hardware, FPV drones) and cars (engineering dynamics, aerodynamic design, and open-road road trips).', section:'About me', action:'More about me', source:'About'},
  {id:'location', match:/where|location|based|hyderabad|city|from/i, text:'I’m based in Hyderabad, India. The Charminar in my portfolio is a little nod to home.', section:'About me', action:'More about me', source:'About'},
  {id:'interests', match:/hobb|interest|outside|fun|movie|coffee|passion/i, text:'Outside design, I love cooking, exploring tech gadgets, admiring cars, 4×4 drives, and practicing mindfulness. I’m deeply spiritual and value intentional living.', section:'About me', action:'More about me', source:'About'},
  {id:'projects', match:/project|work|portfolio|case stud|built|made/i, text:'Explore my projects: Trosky 365, Ryzeup, and HIMSeva HP (2026), FMC (2025 finance hub), and PickleMates (2024 case study).', section:'Projects', action:'Open projects', source:'Projects'},
  {id:'about', match:/yogesh|profile|about|who|what do you do|introduc|designer|background|yourself/i, text:'I’m Yogesh Battula, a Product Designer & AI Vibe Coder based in Hyderabad. Over the past year, I trained like a pro in AI vibe coding to build and ship live products end-to-end. I’m also deeply spiritual, love cooking, and have a strong passion for tech gadgets and cars.', section:'About me', action:'More about me', source:'About'},
];
export function answerProfile(question, previousTopic) {
  const q = question.toLowerCase().replace(/[’']/g,'');
  if (/^(hi|hello|hey|thanks|thank you)[!.\s]*$/.test(q)) return {text:'Hey! I’m Yogesh. Ask me about my projects, experience, skills, or life outside design.', source:'My portfolio'};
  if (/^(tell me more|more|go on|explain more)[!.\s]*$/.test(q) && previousTopic) {
    const topic = topics.find(t=>t.id===previousTopic);
    if(topic) return {...topic, text:`You can explore the full details in ${topic.source}. ${topic.text}`};
  }
  return topics.find(t=>t.match.test(q)) || {text:'I don’t have that detail in my portfolio yet. You can ask me about my experience, projects, tools, location, interests, or résumé.', source:'My portfolio'};
}
